config/routes.rb
BoardGameRails::Application.routes.draw do
  devise_for :users

  root 'application#index'

  get 'users/:id' => 'users#show', :as => :user
  get 'games/search' => 'games#search', :as => :games_search
  get 'games/:id(.:format)/add' => 'games#add', :as => :add_game
  get 'games/:id/remove' => 'games#remove', :as => :remove_game
  match 'games/suggest' => 'games#suggest', :via => [:get, :post], :as => :suggest_game
  resources :plays, except: [:new, :destroy, :show]
  get 'plays/:id' => 'plays#new', :as => :new_play
  get 'collection/search/' => 'games#search_collection', :as => :collection_search
  resources :games

end

app/models/game.rb
class Game < ActiveRecord::Base
  validates_presence_of :name, :min_players, :max_players, :playing_time
  validates_uniqueness_of :name
  validates_numericality_of :min_players, :max_players, :playing_time
  validates_numericality_of :bgg_id, allow_nil: true
  validate :min_players_less_than_or_equal_to_max_players

  has_many :plays
  has_many :players
  has_and_belongs_to_many :users

  scope :played_by_player, ->(f) { f.games }
  scope :played_by_players, ->(fs) { fs.map(&:games).inject(:&) }
  scope :not_played_by_player, ->(f) { all - f.games }
  scope :not_played_by_players, ->(fs) { all - fs.map(&:games).flatten }
  scope :by_number_of_players, ->(num) { where("#{num} BETWEEN min_players AND max_players") }

  private

  def min_players_less_than_or_equal_to_max_players
    errors.add(:max_players, 'must be greater than or equal to min players') if max_players.to_i < min_players.to_i
    errors.add(:min_players, 'must be less than or equal to max players') if min_players.to_i > max_players.to_i
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def add
    if params[:format] == 'bgg'
      bgg = BggApi.new
      game = bgg_to_game(bgg.thing(id: params[:id]))
    else
      game = Game.find(params[:id])
    end
    if current_user.games << game
      redirect_to games_path
    else
      render action: :new
    end
  end

  def create
    if current_user.games << create_game(params[:game])
      redirect_to "/games/#{current_user.games.last.id}"
    else
      render action: :new
    end
  end

  def index
    @games = current_user.games.reorder('name').page(params[:page]) unless current_user.games.nil?
  end

  def remove
    current_user.games.destroy(params[:id])
    redirect_to games_path
  end

  def search
    @results = nil
    if params[:name]
      bgg = BggApi.new
      bgg_results = bgg.search(query: params[:name], type: 'boardgame')['item']
      local_results = Game.where('name like ?', "%#{params[:name]}%")
      @results = format_results(bgg_results, local_results)
      @results = Kaminari.paginate_array(@results).page(params[:page])
    end
  end

  def search_collection
    search_term = params['name'].downcase
    @games = current_user.games.select { |game| game.name.downcase.include?(search_term) }
    render :index
  end

  def show
    if params[:format] == 'bgg'
      bgg = BggApi.new
      @game = bgg_to_game(bgg.thing(id: params[:id]))

    else
      @game = Game.find(params[:id])
    end
  end

  def suggest
    case params[:commit]
    when 'Suggest for this number'
      number_of_players = params[:game][:number_of_players]
      word = number_of_players == 1 ? '#player' : 'players'
      @for_string = "#{number_of_players} #{word}"
      @suggestions = Game.by_number_of_players(number_of_players)
      @suggestions = @suggestions.page(params[:page])
    when 'Suggest for these players'
      names = params[:game][:players].split(',').map(&:strip)
      players = names_to_players(names)
      user = params[:game][:include_me].to_i
      @for_string = names.join(' and ')
      @for_string = names[0..-2].join(', ') + ' and ' + names[-1] if names.count > 2
      if params[:game][:played] == 'Show only games that are new to these people'
        @suggestions = Game.by_number_of_players(players.count + user).not_played_by_players(players)
      else
        @suggestions = Game.by_number_of_players(players.count + user).played_by_players(players)
      end
      @suggestions = Kaminari.paginate_array(@suggestions).page(params[:page])
    end
    render '/games/suggestions' unless params[:commit].nil?
  end

  private

  def bgg_to_game(bgg)
    bgg = bgg['item'].first
    name = bgg['name'].select { |x| x if x['type'] == 'primary' }.first['value']
    Game.find_or_create_by(name: name) do |game|
      game.bgg_id = bgg['id']
      game.name = name
      game.min_players = bgg['minplayers'].first['value']
      game.max_players = bgg['maxplayers'].first['value']
      game.playing_time = bgg['playingtime'].first['value']
      game.description = bgg['description'].first.gsub(/&#10;/, '<br />').gsub(/&#13;/, '<br />')
      game.thumbnail = bgg['thumbnail'].first unless bgg['thumbnail'].nil?
      game.image = bgg['image'].first unless bgg['image'].nil?
    end
  end

  def create_game(params)
    Game.find_or_create_by(name: params[:name]) do |game|
      game.name = params[:name]
      game.min_players = params[:min_players].to_i
      game.max_players = params[:max_players].to_i
      game.playing_time = params[:playing_time_minutes].to_i +
        (params[:playing_time_hours].to_i * 60)
      game.description = params[:description]
    end
  end

  def combine_results(bgg_results, local_results)
    local_names = local_results.map { |x| x[:name].downcase }
    bgg_results = bgg_results.select { |x| x unless local_names.include?(x[:name].downcase) }
    bgg_results + local_results
  end

  def format_bgg_results(bgg_results)
    results = []
    bgg_results.each do |bgg_result|
      game = {}
      game[:name] = bgg_result['name'].first['value']
      game[:bgg_id] = bgg_result['id']
      results << game
    end
    results
  end

  def format_local_results(local_results)
    results = []
    local_results.each do |local_result|
      game = {}
      game[:name] = local_result.name
      game[:game_id] = local_result.id
      game[:min_players] = local_result.min_players
      game[:max_players] = local_result.max_players
      game[:playing_time] = local_result.playing_time
      results << game
    end
    results
  end

  def format_results(bgg_results, local_results)
    bgg_results ||= []
    bgg_results = format_bgg_results(bgg_results)
    local_results = format_local_results(local_results)
    combine_results bgg_results, local_results
  end

  def names_to_players(names)
    names.map { |name| Player.find_or_create_by(name: name) }
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def players_string(game)
    if game.min_players == game.max_players
      if game.min_players == 1
        '1 player'
      else
        "#{game.min_players} players"
      end
    else
      "#{game.min_players}-#{game.max_players} players"
    end
  end

  def play_time_to_string(playing_minutes)
    minutes = playing_minutes % 60
    hours = (playing_minutes - minutes) / 60
    time_string = []
    time_string << stringify_time(hours, 'hour') unless hours == 0
    time_string << stringify_time(minutes, 'minute') unless minutes == 0
    time_string << ' playing time'
    time_string.join(' ')
  end

  def stringify_time(num, word)
    num == 1 ? "1 #{word}" : "#{num} #{word}s"
  end
end

app/views/games/_game.html.haml
%tr.library-game
  %td= link_to game.name, game_path(game.id)
  %td= game.min_players
  %td= game.max_players
  %td= game.playing_time

app/views/games/_result.html.haml
%tr.result
  %td
    - if result[:game_id]
      = link_to result[:name], game_path(result[:game_id])
    - else
      = link_to result[:name], game_path(result[:bgg_id], format: :bgg)

app/views/games/_suggestion.html.haml
%tr.suggestion
  %td= link_to suggestion.name, game_path(suggestion.id)
  %td= suggestion.min_players
  %td= suggestion.max_players
  %td= suggestion.playing_time

app/views/games/index.html.haml
.row
  = form_tag :collection_search, method: :get
  .small-2.columns
    = label_tag :name, "Search by name"
  .small-8.columns
    = text_field_tag :name, nil, required: true, autofocus: true
  .small-2.columns
    = submit_tag("Search", class: "button postfix radius")

.row
  .small-12.columns
    %h3 My Games
    %table.results
      %thead
        %tr
          %th Name
          %th Minimum Players
          %th Maximum Players
          %th Playing Time (minutes)
      %tbody
        - unless @games.empty?
          - @games.each do |game|
            = render game
    = paginate @games unless @games.length < 10

app/views/games/new.html.haml
.row
  .small-12.columns
    %h3 Add Game
    = simple_form_for :game, url: :games, action: :post do |f|
      .section
        .row
          .small-12.columns
            = f.input :name, :autofocus => true, label: "Name"
        .row
          .small-5.columns
            = f.input :min_players, collection: 1..20, label: "Min. Players"
          .small-5.columns.small-offset-2
            = f.input :playing_time_hours, collection: 0..10, label: "Playing Time (hours)"
        .row
          .small-5.columns
            = f.input :max_players, collection: 1..60, label: "Max. Players"
          .small-5.columns.small-offset-2
            = f.input :playing_time_minutes, collection: 0..59, label: "Playing Time (minutes)"
        .row
          .small-12.columns
            = f.input :description, as: :text, label: "Description"
        .row
          .small-12.columns= f.submit "Submit"

app/views/games/search.html.haml
.row
  .small-12.columns
    - if @results.nil?
      %h3 Search For Game To Add
      .section
        = form_tag :games_search, method: :get
        .row
          .small-12.columns
            = label_tag :name, "Search by Name"
        .row.collapse
          .small-9.columns
            = text_field_tag :name, nil, required: true, autofocus: true
          .small-3.columns
            = submit_tag("Submit", class: "button postfix radius")
    - else
      %h3 Game Results
      .row
        .small-12.columns
          - unless @results.empty?
            %table.results
              %thead
                %tr
                  %th Name
              %tbody
                - @results.each do |result|
                  = render partial: "games/result", locals: {result: result}
            = paginate @results
          - else
            No results found

      .row
        .small-4.columns
          %sub Results provided by Board Game Geek
        .small-4.columns.small-offset-4.r-align
          = link_to "Search again?", games_search_path
          %br
          = link_to "Didn't find your game?", new_game_path

app/views/games/show.html.haml
.row
  .small-3.columns
    =image_tag @game.thumbnail
  .small-6.columns
    %h3= @game.name
    %ul
      %li= players_string @game
      %li= play_time_to_string @game.playing_time
  .small-3.columns
    - if current_user.games.include?(@game)
      = link_to "Remove From My Collection", remove_game_path(@game.id), class: "tiny button alert expand"
      = link_to "Play This Game", new_play_path(@game.id), class: "tiny button expand"
    - else
      - if @game.id
        = link_to "Add To My Collection", add_game_path(@game.id), class: "tiny button success expand"
      - else
        = link_to "Add To My Collection", add_game_path(@game.bgg_id, format: :bgg), class: "tiny button success expand"
.row
  .small-12.columns
    %br
      - if @game.description
        = @game.description.html_safe
- if @game.bgg_id
  .row
    .small-12.columns
      Details provided by Board Game Geek

app/views/games/suggest.html.haml
.row
  .small-12.columns
    %h3 Suggest Games
.row
  .small-4.columns
    .section
      %h4 By Number of Players
      = simple_form_for :game, url: :suggest_game, action: :post do |f|
        .row
          .small-12.columns
            = f.input :number_of_players, collection: 1..99, label: "How many players?"
            = f.submit "Suggest for this number", class: "button tiny radius"
  .small-8.columns
    .section
      %h4 By Player Names
      = simple_form_for :game, url: :suggest_game, action: :post do |f|
        .row
          .small-12.columns
            = f.input :players, label: "Players (separated by commas)"
            = f.input :include_me, as: :boolean, label: "Include me in this game", input_html: {checked: true}
            = f.input :played, as: :radio_buttons, collection: ["Show only games that are new to these people", "Show only games these people have played"], checked: "Show only games that are new to these people", label: false
            = f.submit "Suggest for these players", class: "button tiny radius"

app/views/games/suggestions.html.haml
.row
  .small-12.columns
    %h3= "Game suggestions for #{@for_string}"
.row
  .small-12.columns
    - unless @suggestions.empty?
      %table.results
        %thead
          %tr
            %th Name
            %th Minimum Players
            %th Maximum Players
            %th Playing Time (minutes)
        %tbody
          - @suggestions.each do |suggestion|
            = render partial: "games/suggestion", locals: {suggestion: suggestion}
      = paginate @suggestions
    - else
      No games found