config/routes.rb
BoardGameRails::Application.routes.draw do
  devise_for :users

  root 'application#index'

  get 'users/:id' => 'users#show', :as => :user
  get 'games/search' => 'games#search', :as => :games_search
  get 'games/:id(.:format)/add' => 'games#add', :as => :add_game
  get 'games/:id/remove' => 'games#remove', :as => :remove_game
  match 'games/suggest' => 'games#suggest', :via => [:get, :post], :as => :suggest_game
  resources :plays, except: [:new, :destroy, :show]
  get 'plays/:id' => 'plays#new', :as => :new_play
  get 'collection/search/' => 'games#search_collection', :as => :collection_search
  resources :games

end

app/views/layouts/_body.html.haml
%nav.top-bar
  %ul.title-area
    %li
      .name
        %h1#title Board Game Tracker
  %section.top-bar-section
    %ul.left
      %li.divider
      - if current_user
        %li.active
          = link_to "Home", root_path
        %li.divider
        %li.active
          = link_to "Add Game", games_search_path
        %li.divider
        %li.active
          = link_to "Play Game", root_path
        %li.divider
        %li.active
          = link_to "Suggest Game", suggest_game_path
        %li.divider
        %li.active
          = link_to "My Plays", plays_path
    %ul.right
      - if current_user
        %li{:class => 'has_form'}
          = link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %li{:class => 'has_form'}
          = link_to "Sign Up", new_user_registration_path
        %li.divider
        %li{:class => 'has_form'}
          = link_to "Sign In", new_user_session_path

.row
  .small-6.columns.small-offset-3
    -if flash.notice
      .alert-box.success.radius
        = flash.notice
    -if flash.alert
      .alert-box.warning.radius
        = flash.alert
  .small-3.columns

app/views/layouts/_head.html.haml
%title Board Game Tracker
= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
= javascript_include_tag "application", "data-turbolinks-track" => true
= csrf_meta_tags

app/views/layouts/application.html.haml
!!!
%html
  = render "layouts/head"
  %body{class: params[:controller]}
    = render "layouts/body"
    = yield
    :javascript
      $(document).foundation();